server:
    port: 8081
spring:
    cloud:
        config:
            server:
                git:
                    default-label: gateway
                    uri: https://github.com/tomasdaureli/microservicio-springboot
                    search-paths: config-data
    application:
        name: config-service
